<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jiayin Chen">
<meta name="dcterms.date" content="2025-05-05">

<title>Poisson Regression Examples – Jiayin’s Website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-d4d76bf8491c20bad77d141916dc28e1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-6bd9cfa162949bde0a231f530c97869d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Jiayin’s Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#blueprinty-case-study" id="toc-blueprinty-case-study" class="nav-link active" data-scroll-target="#blueprinty-case-study">Blueprinty Case Study</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#comparing-patent-output-by-customer-status" id="toc-comparing-patent-output-by-customer-status" class="nav-link" data-scroll-target="#comparing-patent-output-by-customer-status">Comparing Patent Output by Customer Status</a></li>
  <li><a href="#estimation-of-simple-poisson-model" id="toc-estimation-of-simple-poisson-model" class="nav-link" data-scroll-target="#estimation-of-simple-poisson-model">Estimation of Simple Poisson Model</a></li>
  <li><a href="#likelihood-for-the-poisson-model" id="toc-likelihood-for-the-poisson-model" class="nav-link" data-scroll-target="#likelihood-for-the-poisson-model">Likelihood for the Poisson Model</a></li>
  <li><a href="#analytical-derivation-of-the-mle-for-λ" id="toc-analytical-derivation-of-the-mle-for-λ" class="nav-link" data-scroll-target="#analytical-derivation-of-the-mle-for-λ">Analytical Derivation of the MLE for λ</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  <li><a href="#estimation-of-poisson-regression-model" id="toc-estimation-of-poisson-regression-model" class="nav-link" data-scroll-target="#estimation-of-poisson-regression-model">Estimation of Poisson Regression Model</a></li>
  <li><a href="#interpreting-the-impact-of-blueprinty" id="toc-interpreting-the-impact-of-blueprinty" class="nav-link" data-scroll-target="#interpreting-the-impact-of-blueprinty">Interpreting the Impact of Blueprinty:</a></li>
  </ul></li>
  <li><a href="#airbnb-case-study" id="toc-airbnb-case-study" class="nav-link" data-scroll-target="#airbnb-case-study">AirBnB Case Study</a>
  <ul class="collapse">
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1">Introduction</a></li>
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning">Data Cleaning</a></li>
  <li><a href="#exploratory-analysis-distribution-of-room-types" id="toc-exploratory-analysis-distribution-of-room-types" class="nav-link" data-scroll-target="#exploratory-analysis-distribution-of-room-types">Exploratory Analysis: Distribution of Room Types</a></li>
  <li><a href="#distribution-of-number-of-reviews" id="toc-distribution-of-number-of-reviews" class="nav-link" data-scroll-target="#distribution-of-number-of-reviews">Distribution of Number of Reviews</a></li>
  <li><a href="#price-vs.-review-score-value" id="toc-price-vs.-review-score-value" class="nav-link" data-scroll-target="#price-vs.-review-score-value">Price vs.&nbsp;Review Score (Value)</a></li>
  </ul></li>
  <li><a href="#modeling-number-of-reviews-with-poisson-regression" id="toc-modeling-number-of-reviews-with-poisson-regression" class="nav-link" data-scroll-target="#modeling-number-of-reviews-with-poisson-regression">Modeling Number of Reviews with Poisson Regression</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Poisson Regression Examples</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jiayin Chen </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 5, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="blueprinty-case-study" class="level2">
<h2 class="anchored" data-anchor-id="blueprinty-case-study">Blueprinty Case Study</h2>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>Blueprinty is a small firm that makes software for developing blueprints specifically for submitting patent applications to the US patent office. Their marketing team would like to make the claim that patent applicants using Blueprinty’s software are more successful in getting their patent applications approved. Ideal data to study such an effect might include the success rate of patent applications before using Blueprinty’s software and after using it. Unfortunately, such data is not available.</p>
<p>However, Blueprinty has collected data on 1,500 mature (non-startup) engineering firms. The data include each firm’s number of patents awarded over the last 5 years, regional location, age since incorporation, and whether or not the firm uses Blueprinty’s software. The marketing team would like to use this data to make the claim that firms using Blueprinty’s software are more successful in getting their patent applications approved.</p>
</section>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>To start the analysis, we began by loading the <code>blueprinty.csv</code> dataset into our environment using <code>pandas</code>: The <code>blueprinty</code> dataset contains information on a sample of firms and includes both outcome and explanatory variables relevant for modeling innovation performance — particularly <strong>patent activity</strong>. The main variables in the dataset include:</p>
<ul>
<li><code>patents</code>: Number of patents awarded to each firm over a 5-year period (count outcome).</li>
<li><code>age</code>: Firm age in years.</li>
<li><code>region</code>: Categorical variable representing the firm’s geographical location.</li>
<li><code>iscustomer</code>: Binary indicator (1 if the firm is a Blueprinty customer, 0 otherwise).</li>
</ul>
<div id="4dbc286c" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>blueprinty <span class="op">=</span> pd.read_csv(<span class="st">"blueprinty.csv"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>display(blueprinty.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">patents</th>
<th data-quarto-table-cell-role="th">region</th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">iscustomer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0</td>
<td>Midwest</td>
<td>32.5</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>3</td>
<td>Southwest</td>
<td>37.5</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>4</td>
<td>Northwest</td>
<td>27.0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>3</td>
<td>Northeast</td>
<td>24.5</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>3</td>
<td>Southwest</td>
<td>37.0</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="comparing-patent-output-by-customer-status" class="level3">
<h3 class="anchored" data-anchor-id="comparing-patent-output-by-customer-status">Comparing Patent Output by Customer Status</h3>
<p>To investigate whether Blueprinty customers tend to have more patents, we compared the distribution of <code>patents</code> for customers vs.&nbsp;non-customers both <strong>visually</strong> and <strong>numerically</strong>. To begin, we grouped the dataset by customer status (<code>iscustomer</code>) and calculated the average number of patents. The results show that <strong>Blueprinty customers average 4.13 patents</strong>, compared to <strong>3.47 patents for non-customers</strong>. This suggests a potential positive association between software usage and innovation outcomes.</p>
<p>To visualize this relationship, we created a histogram of patent counts stratified by customer status. Both groups display a <strong>right-skewed distribution</strong>, typical of count data like patents. However, the histogram shows that <strong>Blueprinty customers are more concentrated at higher patent counts</strong>, with their distribution clearly shifted to the right relative to non-customers. This provides initial descriptive support for the hypothesis that Blueprinty software may enhance innovation performance.</p>
<p>This preliminary finding suggests a potential positive association between customer status and patent count, which will be investigated further using Poisson regression.</p>
<div id="49e9a851" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>))</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>sns.histplot(data<span class="op">=</span>blueprinty, x<span class="op">=</span><span class="st">"patents"</span>, hue<span class="op">=</span><span class="st">"iscustomer"</span>, binwidth<span class="op">=</span><span class="dv">1</span>, multiple<span class="op">=</span><span class="st">"dodge"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Histogram of Patents by Customer Status"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Number of Patents"</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Count"</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>plt.legend(title<span class="op">=</span><span class="st">"Customer Status"</span>, labels<span class="op">=</span>[<span class="st">"Non-Customer"</span>, <span class="st">"Customer"</span>])</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>means_by_status <span class="op">=</span> blueprinty.groupby(<span class="st">"iscustomer"</span>)[<span class="st">"patents"</span>].mean().reset_index()</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>display(means_by_status)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-3-output-1.png" width="816" height="449" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">iscustomer</th>
<th data-quarto-table-cell-role="th">patents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0</td>
<td>3.473013</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1</td>
<td>4.133056</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Blueprinty customers are not selected at random. It may be important to account for systematic differences in the age and regional location of customers vs non-customers.</p>
<p>To assess whether Blueprinty customers differ systematically from non-customers, we explored variation in geographic region by customer status. This is an important step in evaluating potential confounding variables, which could bias the observed relationship between software usage and patent outcomes.</p>
<p>We visualized the regional distribution of firms across customer categories using a bar chart. The results reveal a clear pattern: the Northeast region accounts for a disproportionately high number of Blueprinty customers, while other regions — including the Midwest, Northwest, South, and Southwest — are more heavily populated by non-customers. This suggests that customer status is not randomly assigned with respect to geography.</p>
<div id="84096995" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare average age by customer status</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>age <span class="op">=</span> blueprinty.groupby(<span class="st">"iscustomer"</span>)[<span class="st">"age"</span>]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare region distribution by customer status using counts</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>region_counts <span class="op">=</span> pd.crosstab(blueprinty[<span class="st">"region"</span>], blueprinty[<span class="st">"iscustomer"</span>])</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>region_counts.columns <span class="op">=</span> [<span class="st">"Non-Customer"</span>, <span class="st">"Customer"</span>]</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Bar plot of regional distributions (counts)</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>region_counts.plot(kind<span class="op">=</span><span class="st">"bar"</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>))</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Regional Distribution by Customer Status"</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Count"</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Region"</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>plt.legend(title<span class="op">=</span><span class="st">"Customer Status"</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-4-output-1.png" width="950" height="470" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The implication is that region may influence both the likelihood of adopting Blueprinty software and the number of patents awarded. For instance, firms in the Northeast may have better access to innovation infrastructure, denser professional networks, or different industry concentrations — all of which could affect patenting behavior independently of software usage.</p>
</section>
<section id="estimation-of-simple-poisson-model" class="level3">
<h3 class="anchored" data-anchor-id="estimation-of-simple-poisson-model">Estimation of Simple Poisson Model</h3>
<p>Since our outcome variable of interest can only be small integer values per a set unit of time, we can use a Poisson density to model the number of patents awarded to each engineering firm over the last 5 years. We start by estimating a simple Poisson model via Maximum Likelihood.</p>
</section>
<section id="likelihood-for-the-poisson-model" class="level3">
<h3 class="anchored" data-anchor-id="likelihood-for-the-poisson-model">Likelihood for the Poisson Model</h3>
<p>We model the number of patents <span class="math inline">\(Y_i\)</span> for each firm <span class="math inline">\(i\)</span> as Poisson-distributed:</p>
<p><span class="math display">\[
Y_i \sim \text{Poisson}(\lambda)
\]</span></p>
<p>The probability mass function of the Poisson distribution is:</p>
<p><span class="math display">\[
f(Y_i \mid \lambda) = \frac{e^{-\lambda} \lambda^{Y_i}}{Y_i!}
\]</span></p>
<p>Assuming independent observations for <span class="math inline">\(i = 1, 2, \dots, n\)</span>, the <strong>likelihood function</strong> for the full sample is:</p>
<p><span class="math display">\[
\mathcal{L}(\lambda) = \prod_{i=1}^{n} \frac{e^{-\lambda} \lambda^{Y_i}}{Y_i!}
\]</span></p>
<p>Taking the natural logarithm, the <strong>log-likelihood function</strong> becomes:</p>
<p><span class="math display">\[
\log \mathcal{L}(\lambda) = \sum_{i=1}^{n} \left( -\lambda + Y_i \log(\lambda) - \log(Y_i!) \right)
\]</span></p>
<p>This log-likelihood will be the basis for estimating the parameter <span class="math inline">\(\lambda\)</span> using Maximum Likelihood Estimation.</p>
<div id="d3698f29" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.special <span class="im">import</span> gammaln</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_log_likelihood(lmbda, y):</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Compute the log-likelihood of Poisson-distributed data y given parameter lambda.</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters:</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co">    - lmbda (float): The Poisson rate parameter (must be &gt; 0)</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co">    - y (array-like): Observed count data</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="co">    - float: The total log-likelihood value</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> lmbda <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="op">-</span>np.inf  <span class="co"># log-likelihood is undefined for non-positive lambda</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> np.asarray(y)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    log_likelihood <span class="op">=</span> np.<span class="bu">sum</span>(<span class="op">-</span>lmbda <span class="op">+</span> y <span class="op">*</span> np.log(lmbda) <span class="op">-</span> gammaln(y <span class="op">+</span> <span class="dv">1</span>))</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> log_likelihood</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="38822a68" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Log-likelihood function</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_log_likelihood(lmbda, y):</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> lmbda <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="op">-</span>np.inf</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> np.asarray(y)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.<span class="bu">sum</span>(<span class="op">-</span>lmbda <span class="op">+</span> y <span class="op">*</span> np.log(lmbda) <span class="op">-</span> gammaln(y <span class="op">+</span> <span class="dv">1</span>))</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Observed count data: number of patents</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>y_data <span class="op">=</span> blueprinty[<span class="st">"patents"</span>].values</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Range of lambda values to evaluate</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>lambda_values <span class="op">=</span> np.linspace(<span class="fl">0.1</span>, <span class="dv">20</span>, <span class="dv">200</span>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute log-likelihoods</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>log_likelihoods <span class="op">=</span> [poisson_log_likelihood(lmbda, y_data) <span class="cf">for</span> lmbda <span class="kw">in</span> lambda_values]</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the results</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>plt.plot(lambda_values, log_likelihoods, label<span class="op">=</span><span class="st">'Log-Likelihood'</span>, color<span class="op">=</span><span class="st">'darkblue'</span>)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>plt.axvline(x<span class="op">=</span>lambda_values[np.argmax(log_likelihoods)], color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="st">'MLE'</span>)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Log-Likelihood of Poisson Model over λ"</span>)</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"λ (Lambda)"</span>)</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Log-Likelihood"</span>)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-6-output-1.png" width="950" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="analytical-derivation-of-the-mle-for-λ" class="level3">
<h3 class="anchored" data-anchor-id="analytical-derivation-of-the-mle-for-λ">Analytical Derivation of the MLE for λ</h3>
<p>To derive the maximum likelihood estimator (MLE) for ( ), we start with the log-likelihood function of the Poisson model:</p>
<p><span class="math display">\[
\log \mathcal{L}(\lambda) = \sum_{i=1}^{n} \left( -\lambda + Y_i \log(\lambda) - \log(Y_i!) \right)
\]</span></p>
<p>We take the first derivative with respect to ( ):</p>
<p><span class="math display">\[
\frac{d}{d\lambda} \log \mathcal{L}(\lambda) = \sum_{i=1}^{n} \left( -1 + \frac{Y_i}{\lambda} \right)
= -n + \frac{1}{\lambda} \sum_{i=1}^{n} Y_i
\]</span></p>
<p>Set the derivative equal to zero to find the maximizer:</p>
<p><span class="math display">\[
-n + \frac{1}{\lambda} \sum_{i=1}^{n} Y_i = 0
\]</span></p>
<p>Solving for ( ):</p>
<p><span class="math display">\[
\lambda = \frac{1}{n} \sum_{i=1}^{n} Y_i = \bar{Y}
\]</span> Thus, the MLE of ( ) is the sample mean, ( {y} ), which matches the expectation of the Poisson parameter:</p>
<p><span class="math display">\[
\lambda_{\text{MLE}} = \bar{y}
\]</span></p>
<div id="17b415be" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>lambda_mle_analytical <span class="op">=</span> np.mean(y_data)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Analytical MLE for λ = </span><span class="sc">{</span>lambda_mle_analytical<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analytical MLE for λ = 3.6847</code></pre>
</div>
</div>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<p>The MLE for ( ) is simply the sample mean ( {Y} ), which aligns with our intuition. Since the Poisson distribution has mean ( ), it’s natural that the average observed count provides the</p>
<div id="70bed3d0" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize_scalar</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define negative log-likelihood to minimize</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> neg_poisson_log_likelihood(lmbda, y):</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>poisson_log_likelihood(lmbda, y)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Optimize over a reasonable range of lambda values</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> minimize_scalar(</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    fun<span class="op">=</span>neg_poisson_log_likelihood,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    args<span class="op">=</span>(y_data,),</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    bounds<span class="op">=</span>(<span class="fl">0.01</span>, <span class="dv">20</span>),</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    method<span class="op">=</span><span class="st">'bounded'</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>lambda_mle <span class="op">=</span> result.x</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>lambda_mle</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"MLE for λ: </span><span class="sc">{</span>lambda_mle<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>MLE for λ: 3.6847</code></pre>
</div>
</div>
</section>
<section id="estimation-of-poisson-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="estimation-of-poisson-regression-model">Estimation of Poisson Regression Model</h3>
<p>Next, we extend our simple Poisson model to a Poisson Regression Model such that <span class="math inline">\(Y_i = \text{Poisson}(\lambda_i)\)</span> where <span class="math inline">\(\lambda_i = \exp(X_i'\beta)\)</span>. The interpretation is that the success rate of patent awards is not constant across all firms (<span class="math inline">\(\lambda\)</span>) but rather is a function of firm characteristics <span class="math inline">\(X_i\)</span>. Specifically, we will use the covariates age, age squared, region, and whether the firm is a customer of Blueprinty.</p>
<p>To move beyond the constant-rate Poisson model, I extended the framework to a Poisson regression, allowing the expected number of patents ( _i ) to vary across firms based on observed characteristics. Specifically, I modeled the outcome as:</p>
<p><span class="math display">\[
Y_i \sim \text{Poisson}(\lambda_i), \quad \text{where } \lambda_i = \exp(X_i^\top \beta)
\]</span></p>
<p>This specification assumes that the log of the expected number of patents is a linear function of covariates.</p>
<p>To operationalize this, I constructed a design matrix ( X ) that includes firm age, age squared (to capture non-linear effects), a binary indicator for whether the firm is a Blueprinty customer, and dummy variables for region (with one region omitted as the reference group). I then defined a log-likelihood function for the Poisson model and used <code>scipy.optimize.minimize</code> with the BFGS method to estimate the vector of coefficients ( ). I included a clipping step on the linear predictor to avoid numerical overflow when exponentiating large values.</p>
<p>After optimization, I extracted the maximum likelihood estimates for each coefficient as well as the standard errors from the inverse Hessian matrix. These results are presented in a summary table showing the effect of each covariate on the expected number of patents. This regression framework allows us to estimate the adjusted association between Blueprinty usage and innovation outcomes while controlling for other important firm characteristics such as age and location.</p>
<div id="201f5f1e" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardize age and age_squared</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> blueprinty.copy()</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"age_squared"</span>] <span class="op">=</span> df[<span class="st">"age"</span>] <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create model matrix</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>region_dummies <span class="op">=</span> pd.get_dummies(df[<span class="st">"region"</span>], drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>X_df <span class="op">=</span> pd.concat([</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    pd.Series(<span class="dv">1</span>, index<span class="op">=</span>df.index, name<span class="op">=</span><span class="st">"intercept"</span>),</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    df[[<span class="st">"age"</span>, <span class="st">"age_squared"</span>, <span class="st">"iscustomer"</span>]],</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    region_dummies</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>X_matrix <span class="op">=</span> X_df.values</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">"patents"</span>].values</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Log-likelihood</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> neg_log_likelihood(beta, y, X):</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>    beta <span class="op">=</span> np.asarray(beta, dtype<span class="op">=</span>np.float64)</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> np.asarray(X, dtype<span class="op">=</span>np.float64)</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> np.asarray(y, dtype<span class="op">=</span>np.float64)</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>    eta <span class="op">=</span> np.clip(X <span class="op">@</span> beta, <span class="op">-</span><span class="dv">20</span>, <span class="dv">20</span>)</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>    lambda_i <span class="op">=</span> np.exp(eta)</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>np.<span class="bu">sum</span>(<span class="op">-</span>lambda_i <span class="op">+</span> y <span class="op">*</span> np.log(lambda_i) <span class="op">-</span> gammaln(y <span class="op">+</span> <span class="dv">1</span>))</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-run optimization safely</span></span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>beta_start <span class="op">=</span> np.zeros(X_matrix.shape[<span class="dv">1</span>])</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> minimize(</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>    fun<span class="op">=</span>neg_log_likelihood,</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>    x0<span class="op">=</span>beta_start,</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>    args<span class="op">=</span>(y, X_matrix),</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a>    method<span class="op">=</span><span class="st">"BFGS"</span></span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract results</span></span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a>beta_hat <span class="op">=</span> result.x</span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>hessian_inv <span class="op">=</span> result.hess_inv</span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a>standard_errors <span class="op">=</span> np.sqrt(np.diag(hessian_inv))</span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Present results</span></span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a>results_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Coefficient"</span>: beta_hat,</span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Std. Error"</span>: standard_errors</span>
<span id="cb10-46"><a href="#cb10-46" aria-hidden="true" tabindex="-1"></a>}, index<span class="op">=</span>X_df.columns)</span>
<span id="cb10-47"><a href="#cb10-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-48"><a href="#cb10-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-49"><a href="#cb10-49" aria-hidden="true" tabindex="-1"></a>results_df </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Coefficient</th>
<th data-quarto-table-cell-role="th">Std. Error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">intercept</td>
<td>-0.509956</td>
<td>0.193060</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">age</td>
<td>0.148702</td>
<td>0.014461</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">age_squared</td>
<td>-0.002972</td>
<td>0.000266</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">iscustomer</td>
<td>0.207600</td>
<td>0.032934</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Northeast</td>
<td>0.029159</td>
<td>0.046770</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Northwest</td>
<td>-0.017578</td>
<td>0.057230</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">South</td>
<td>0.056567</td>
<td>0.056244</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Southwest</td>
<td>0.050589</td>
<td>0.049642</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>To estimate the Poisson regression model using a built-in method, I employed the <code>statsmodels</code> library in Python. This approach serves as a validation of the custom maximum likelihood implementation done previously. I began by reconstructing the design matrix ( X ) to include all relevant predictors. Specifically, I included: firm age, the square of firm age (to capture potential non-linear effects), a binary indicator for whether the firm is a Blueprinty customer, and dummy variables for firm region (excluding one region as the baseline category to avoid multicollinearity). I also explicitly added a constant column to allow estimation of an intercept term.</p>
<p>Once the design matrix was created, I ensured that all values in both the feature matrix and the outcome vector were of type <code>float64</code> to meet the requirements of the <code>statsmodels</code> GLM framework. I then specified and fitted a Poisson generalized linear model using the canonical log link function. The outcome variable was <code>patents</code>, which represents the count of patents awarded to each firm.</p>
<p>The model was estimated using the <code>GLM()</code> and <code>.fit()</code> methods provided by <code>statsmodels</code>, and the output includes coefficient estimates along with standard errors, z-values, and associated p-values. These results provide a formally estimated Poisson regression model that can be used to interpret how firm characteristics are associated with patent output, while adjusting for potential confounding variables.</p>
<div id="51d65e6c" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardize age and age_squared</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> blueprinty.copy()</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"age_squared"</span>] <span class="op">=</span> df[<span class="st">"age"</span>] <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create model matrix</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>region_dummies <span class="op">=</span> pd.get_dummies(df[<span class="st">"region"</span>], drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>X_df <span class="op">=</span> pd.concat([</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    pd.Series(<span class="dv">1</span>, index<span class="op">=</span>df.index, name<span class="op">=</span><span class="st">"intercept"</span>),</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    df[[<span class="st">"age"</span>, <span class="st">"age_squared"</span>, <span class="st">"iscustomer"</span>]],</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    region_dummies</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>X_matrix <span class="op">=</span> X_df.values</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>y_vector <span class="op">=</span> df[<span class="st">"patents"</span>].values</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure correct data types</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>X_matrix <span class="op">=</span> X_matrix.astype(np.float64)</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> y.astype(np.float64)</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit Poisson GLM</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>glm_model <span class="op">=</span> sm.GLM(y, X_matrix, family<span class="op">=</span>sm.families.Poisson())</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>glm_results <span class="op">=</span> glm_model.fit()</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Display results</span></span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>glm_results.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Generalized Linear Model Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>y</td>
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>1500</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>GLM</td>
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>1492</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Model Family:</td>
<td>Poisson</td>
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>7</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Link Function:</td>
<td>Log</td>
<td data-quarto-table-cell-role="th">Scale:</td>
<td>1.0000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>IRLS</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-3258.1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Tue, 06 May 2025</td>
<td data-quarto-table-cell-role="th">Deviance:</td>
<td>2143.3</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>20:29:28</td>
<td data-quarto-table-cell-role="th">Pearson chi2:</td>
<td>2.07e+03</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. Iterations:</td>
<td>5</td>
<td data-quarto-table-cell-role="th">Pseudo R-squ. (CS):</td>
<td>0.1360</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">z</td>
<td data-quarto-table-cell-role="th">P&gt;|z|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">const</td>
<td>-0.5089</td>
<td>0.183</td>
<td>-2.778</td>
<td>0.005</td>
<td>-0.868</td>
<td>-0.150</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">x1</td>
<td>0.1486</td>
<td>0.014</td>
<td>10.716</td>
<td>0.000</td>
<td>0.121</td>
<td>0.176</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">x2</td>
<td>-0.0030</td>
<td>0.000</td>
<td>-11.513</td>
<td>0.000</td>
<td>-0.003</td>
<td>-0.002</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">x3</td>
<td>0.2076</td>
<td>0.031</td>
<td>6.719</td>
<td>0.000</td>
<td>0.147</td>
<td>0.268</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">x4</td>
<td>0.0292</td>
<td>0.044</td>
<td>0.669</td>
<td>0.504</td>
<td>-0.056</td>
<td>0.115</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">x5</td>
<td>-0.0176</td>
<td>0.054</td>
<td>-0.327</td>
<td>0.744</td>
<td>-0.123</td>
<td>0.088</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">x6</td>
<td>0.0566</td>
<td>0.053</td>
<td>1.074</td>
<td>0.283</td>
<td>-0.047</td>
<td>0.160</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">x7</td>
<td>0.0506</td>
<td>0.047</td>
<td>1.072</td>
<td>0.284</td>
<td>-0.042</td>
<td>0.143</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Interpreting the Poisson Regression Coefficients:</p>
<p>The Poisson regression model estimates the log of the expected number of patents as a function of several firm-level characteristics. The intercept term (beta_0 = -0.510) reflects the log expected number of patents for a firm with all covariates equal to zero — a hypothetical baseline that is not directly interpretable but serves as a reference point.</p>
<p>The coefficient on <code>age</code> (x1 = 0.149) is positive and statistically significant, suggesting that older firms tend to produce more patents. Specifically, each one-unit increase in age is associated with an approximate <strong>16% increase</strong> in the expected number of patents.</p>
<p>The variable <code>iscustomer</code> (x2 = 0.208) is also highly significant and indicates that, on average, <strong>Blueprinty customers are expected to produce approximately 23% more patents</strong> than non-customers, holding all else constant. This provides strong evidence that using Blueprinty software is positively associated with innovation outcomes.</p>
<p>The coefficient on <code>age_squared</code> (x3 = -0.003) is small but negative, suggesting <strong>diminishing marginal returns</strong> to age — as firms get older, the positive effect of age on patent output begins to level off.</p>
<p>The remaining variables capture <strong>regional fixed effects</strong>, with the reference category being the region omitted from the model (not shown in the table). None of the regional coefficients — <code>region_Northeast</code> (x4), <code>region_Northwest</code> (x5), <code>region_South</code> (x6), and <code>region_Southwest</code> (x7) — are statistically significant, implying that after accounting for firm age and customer status, location does not substantially affect the number of patents.</p>
<p>Overall, the model suggests that <strong>Blueprinty usage and firm age</strong> are the primary drivers of variation in patenting activity, with only minor contributions from regional differences.</p>
</section>
<section id="interpreting-the-impact-of-blueprinty" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-the-impact-of-blueprinty">Interpreting the Impact of Blueprinty:</h3>
<p>To interpret the practical impact of being a Blueprinty customer, we conduct a counterfactual prediction exercise. We create two hypothetical datasets:</p>
<ul>
<li><strong><code>X₀</code></strong>: All firms are treated as non-customers (<code>iscustomer = 0</code>)</li>
<li><strong><code>X₁</code></strong>: All firms are treated as customers (<code>iscustomer = 1</code>)</li>
</ul>
<p>Using our estimated Poisson regression coefficients, we calculate the predicted number of patents for each firm in both scenarios:</p>
<p><span class="math display">\[
\hat{Y}_0 = \exp(X_0 \hat{\beta}), \quad \hat{Y}_1 = \exp(X_1 \hat{\beta})
\]</span></p>
<p>The difference between these predictions represents the model-implied effect of using Blueprinty. Averaging the differences across all firms gives us the estimated treatment effect:</p>
<p><span class="math display">\[
\text{Average}(\hat{Y}_1 - \hat{Y}_0) \approx 0.79
\]</span></p>
<div id="9eb2991c" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict counterfactuals</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>beta_hat <span class="op">=</span> result.x</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>X_0 <span class="op">=</span> X_df.copy()</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>X_0[<span class="st">"iscustomer"</span>] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>X_1 <span class="op">=</span> X_df.copy()</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>X_1[<span class="st">"iscustomer"</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>X0_matrix <span class="op">=</span> X_0.values</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>X1_matrix <span class="op">=</span> X_1.values</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>X0_matrix  <span class="op">=</span> np.asarray(X0_matrix , dtype<span class="op">=</span>np.float64)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>X1_matrix  <span class="op">=</span> np.asarray(X1_matrix , dtype<span class="op">=</span>np.float64)</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>lambda_0 <span class="op">=</span> np.exp(np.clip(X0_matrix <span class="op">@</span> beta_hat, <span class="op">-</span><span class="dv">10</span>, <span class="dv">10</span>))</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>lambda_1 <span class="op">=</span> np.exp(np.clip(X1_matrix <span class="op">@</span> beta_hat, <span class="op">-</span><span class="dv">10</span>, <span class="dv">10</span>))</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Average difference in predicted patent counts</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>average_difference <span class="op">=</span> np.mean(lambda_1 <span class="op">-</span> lambda_0)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>average_difference</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Average expected effect of using Blueprinty: </span><span class="sc">{</span>average_difference<span class="sc">:.4f}</span><span class="ss"> patents"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Average expected effect of using Blueprinty: 0.7928 patents</code></pre>
</div>
</div>
<p>The results show that, on average, firms that are modeled as Blueprinty customers are predicted to receive approximately <strong>0.79 more patents</strong> than they would as non-customers, holding firm age and region constant. This provides strong evidence that Blueprinty usage is positively associated with increased patent activity. While this estimate does not definitively establish causality due to the observational nature of the data, it does reflect a meaningful association that persists even after adjusting for potential confounders. The finding reinforces the earlier coefficient-based interpretation and supports the hypothesis that Blueprinty’s tools contribute to improved innovation performance.</p>
</section>
</section>
<section id="airbnb-case-study" class="level2">
<h2 class="anchored" data-anchor-id="airbnb-case-study">AirBnB Case Study</h2>
<section id="introduction-1" class="level3">
<h3 class="anchored" data-anchor-id="introduction-1">Introduction</h3>
<p>AirBnB is a popular platform for booking short-term rentals. In March 2017, students Annika Awad, Evan Lebo, and Anna Linden scraped of 40,000 Airbnb listings from New York City. The data include the following variables:</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Variable Definitions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>- `id` = unique ID number for each unit
- `last_scraped` = date when information scraped
- `host_since` = date when host first listed the unit on Airbnb
- `days` = `last_scraped` - `host_since` = number of days the unit has been listed
- `room_type` = Entire home/apt., Private room, or Shared room
- `bathrooms` = number of bathrooms
- `bedrooms` = number of bedrooms
- `price` = price per night (dollars)
- `number_of_reviews` = number of reviews for the unit on Airbnb
- `review_scores_cleanliness` = a cleanliness score from reviews (1-10)
- `review_scores_location` = a "quality of location" score from reviews (1-10)
- `review_scores_value` = a "quality of value" score from reviews (1-10)
- `instant_bookable` = "t" if instantly bookable, "f" if not</code></pre>
</div>
</div>
</div>
</section>
<section id="data-cleaning" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning">Data Cleaning</h3>
<p>Before modeling, we performed a series of data cleaning steps to ensure the dataset was consistent, complete, and suitable for Poisson regression.</p>
<ol type="1">
<li><strong>Dropped rows with missing values in critical columns</strong>:<br>
We removed observations where any of the following key identifying or structural variables were missing:
<ul>
<li><code>id</code>, <code>days</code>, <code>last_scraped</code>, <code>host_since</code>, <code>room_type</code>, <code>instant_bookable</code><br>
These variables are essential for defining the listing, its availability, and booking characteristics. Missing values in these columns would make the observation unusable for analysis or modeling.</li>
</ul></li>
<li><strong>Filled missing values in integer-like columns with rounded mean</strong>:
<ul>
<li>For <code>bathrooms</code> and <code>bedrooms</code>, we calculated the column mean and rounded it to the nearest integer before filling missing values.<br>
This approach preserves the variable’s intended numeric structure while avoiding fractional values that don’t make sense.</li>
</ul></li>
<li><strong>Filled missing values in continuous variables with their mean</strong>:
<ul>
<li>For columns like <code>price</code>, <code>number_of_reviews</code>, <code>review_scores_cleanliness</code>, <code>review_scores_location</code>, and <code>review_scores_value</code>, missing values were filled with the column mean.<br>
This standard imputation method avoids dropping additional rows and preserves sample size, while assuming the missingness is relatively random.</li>
</ul></li>
</ol>
<p>These cleaning steps ensure the dataset is free of nulls in relevant variables and suitable for exploratory data analysis and regression modeling.</p>
<div id="24ae88db" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"airbnb.csv"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>df.dropna(subset<span class="op">=</span>[<span class="st">"id"</span>, <span class="st">"days"</span>, <span class="st">"last_scraped"</span>, <span class="st">"host_since"</span>, <span class="st">"room_type"</span>, <span class="st">"instant_bookable"</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> [<span class="st">"bathrooms"</span>, <span class="st">"bedrooms"</span>]:</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    mean_val <span class="op">=</span> df[col].dropna().mean()</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    df[col] <span class="op">=</span> df[col].fillna(<span class="bu">int</span>(mean_val))</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>cols_to_fill <span class="op">=</span> [</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"price"</span>, <span class="st">"number_of_reviews"</span>, <span class="st">"review_scores_cleanliness"</span>,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"review_scores_location"</span>, <span class="st">"review_scores_value"</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> cols_to_fill:</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>    mean_val <span class="op">=</span> df[col].dropna().mean()</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>    df[col] <span class="op">=</span> df[col].fillna(mean_val)</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Unnamed: 0</th>
<th data-quarto-table-cell-role="th">id</th>
<th data-quarto-table-cell-role="th">days</th>
<th data-quarto-table-cell-role="th">last_scraped</th>
<th data-quarto-table-cell-role="th">host_since</th>
<th data-quarto-table-cell-role="th">room_type</th>
<th data-quarto-table-cell-role="th">bathrooms</th>
<th data-quarto-table-cell-role="th">bedrooms</th>
<th data-quarto-table-cell-role="th">price</th>
<th data-quarto-table-cell-role="th">number_of_reviews</th>
<th data-quarto-table-cell-role="th">review_scores_cleanliness</th>
<th data-quarto-table-cell-role="th">review_scores_location</th>
<th data-quarto-table-cell-role="th">review_scores_value</th>
<th data-quarto-table-cell-role="th">instant_bookable</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>2515</td>
<td>3130</td>
<td>4/2/2017</td>
<td>9/6/2008</td>
<td>Private room</td>
<td>1.0</td>
<td>1.0</td>
<td>59</td>
<td>150</td>
<td>9.000000</td>
<td>9.0000</td>
<td>9.000000</td>
<td>f</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2</td>
<td>2595</td>
<td>3127</td>
<td>4/2/2017</td>
<td>9/9/2008</td>
<td>Entire home/apt</td>
<td>1.0</td>
<td>0.0</td>
<td>230</td>
<td>20</td>
<td>9.000000</td>
<td>10.0000</td>
<td>9.000000</td>
<td>f</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3</td>
<td>3647</td>
<td>3050</td>
<td>4/2/2017</td>
<td>11/25/2008</td>
<td>Private room</td>
<td>1.0</td>
<td>1.0</td>
<td>150</td>
<td>0</td>
<td>9.198376</td>
<td>9.4136</td>
<td>9.331587</td>
<td>f</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>4</td>
<td>3831</td>
<td>3038</td>
<td>4/2/2017</td>
<td>12/7/2008</td>
<td>Entire home/apt</td>
<td>1.0</td>
<td>1.0</td>
<td>89</td>
<td>116</td>
<td>9.000000</td>
<td>9.0000</td>
<td>9.000000</td>
<td>f</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>5</td>
<td>4611</td>
<td>3012</td>
<td>4/2/2017</td>
<td>1/2/2009</td>
<td>Private room</td>
<td>1.0</td>
<td>1.0</td>
<td>39</td>
<td>93</td>
<td>9.000000</td>
<td>8.0000</td>
<td>9.000000</td>
<td>t</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">40623</td>
<td>40624</td>
<td>18008937</td>
<td>266</td>
<td>4/2/2017</td>
<td>7/10/2016</td>
<td>Entire home/apt</td>
<td>1.5</td>
<td>2.0</td>
<td>150</td>
<td>0</td>
<td>9.198376</td>
<td>9.4136</td>
<td>9.331587</td>
<td>t</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">40624</td>
<td>40625</td>
<td>18009045</td>
<td>366</td>
<td>4/2/2017</td>
<td>4/1/2016</td>
<td>Private room</td>
<td>1.0</td>
<td>1.0</td>
<td>125</td>
<td>0</td>
<td>9.198376</td>
<td>9.4136</td>
<td>9.331587</td>
<td>f</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">40625</td>
<td>40626</td>
<td>18009065</td>
<td>587</td>
<td>4/2/2017</td>
<td>8/24/2015</td>
<td>Private room</td>
<td>1.0</td>
<td>1.0</td>
<td>80</td>
<td>0</td>
<td>9.198376</td>
<td>9.4136</td>
<td>9.331587</td>
<td>t</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">40626</td>
<td>40627</td>
<td>18009650</td>
<td>335</td>
<td>4/2/2017</td>
<td>5/2/2016</td>
<td>Private room</td>
<td>1.0</td>
<td>1.0</td>
<td>69</td>
<td>0</td>
<td>9.198376</td>
<td>9.4136</td>
<td>9.331587</td>
<td>t</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">40627</td>
<td>40628</td>
<td>18009669</td>
<td>1</td>
<td>4/2/2017</td>
<td>4/1/2017</td>
<td>Entire home/apt</td>
<td>1.0</td>
<td>1.0</td>
<td>115</td>
<td>0</td>
<td>9.198376</td>
<td>9.4136</td>
<td>9.331587</td>
<td>t</td>
</tr>
</tbody>
</table>

<p>40593 rows × 14 columns</p>
</div>
</div>
</div>
</section>
<section id="exploratory-analysis-distribution-of-room-types" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-analysis-distribution-of-room-types">Exploratory Analysis: Distribution of Room Types</h3>
<p>To understand the types of listings available on Airbnb in New York City, we visualized the distribution of the <code>room_type</code> variable using a bar chart.</p>
<div id="221e15da" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>room_counts <span class="op">=</span> df[<span class="st">"room_type"</span>].value_counts()</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>sns.barplot(x<span class="op">=</span>room_counts.index, y<span class="op">=</span>room_counts.values)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Distribution of Room Types"</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Room Type"</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Number of Listings"</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>plt.grid(axis<span class="op">=</span><span class="st">'y'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-13-output-1.png" width="684" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The distribution of room types among Airbnb listings in New York City reveals that the vast majority of listings are either <strong>entire homes/apartments</strong> or <strong>private rooms</strong>, each category accounting for nearly 20,000 listings. In contrast, <strong>shared rooms</strong> represent only a small fraction of the market, indicating that such accommodations are relatively uncommon. This pattern suggests that most Airbnb hosts cater to travelers who prioritize privacy, either through full-unit rentals or private sleeping spaces. From a modeling perspective, <strong>room type</strong> is likely to be an informative categorical variable, as it may capture meaningful variation in factors such as price, demand, and guest experience. Accordingly, it should be included in any predictive models of review counts or booking behavior. ### Exploratory Analysis: Distribution of Airbnb Prices</p>
<p>To explore pricing across Airbnb listings, we examined the distribution of the <code>price</code> variable using a histogram with a kernel density estimate (KDE) overlay.</p>
<div id="ae35dec5" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Summary statistics for 'price':"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">"price"</span>].describe())</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>sns.histplot(df[<span class="st">"price"</span>], bins<span class="op">=</span><span class="dv">50</span>, kde<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Distribution of Airbnb Prices"</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Price"</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Frequency"</span>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Summary statistics for 'price':
count    40593.000000
mean       144.762250
std        210.703908
min         10.000000
25%         70.000000
50%        100.000000
75%        170.000000
max      10000.000000
Name: price, dtype: float64</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-14-output-2.png" width="833" height="523" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Insights:</p>
<ul>
<li>The distribution of prices is <strong>strongly right-skewed</strong>, with the vast majority of listings priced below $500 per night.</li>
<li>The x-axis stretches to $10,000, which suggests the presence of <strong>extreme outliers</strong> — high-priced luxury listings that are rare but heavily affect the scale of the histogram.</li>
<li>The mode of the distribution (most common price point) appears to be under $200.</li>
</ul>
<p>These outliers could heavily influence the mean and regression results. It may be useful to filter or winsorize extreme price values in further analysis.</p>
<p>The initial histogram of Airbnb prices revealed a highly skewed distribution, with some listings priced as high as $10,000 per night. These extreme values are likely outliers and can disproportionately influence summary statistics and regression models.</p>
<p>To address this, we quantified and removed listings with prices above $1,000:</p>
<div id="db05e984" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>high_price_count <span class="op">=</span> (df[<span class="st">"price"</span>] <span class="op">&gt;</span> <span class="dv">1000</span>).<span class="bu">sum</span>()</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Number of listings with price &gt; 1000: </span><span class="sc">{</span>high_price_count<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df[df[<span class="st">"price"</span>] <span class="op">&lt;=</span> <span class="dv">1000</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of listings with price &gt; 1000: 146</code></pre>
</div>
</div>
<p>There were <strong>146 listings</strong> identified and removed based on the $1,000 price threshold. These represent high-end, likely luxury properties that are <strong>not representative</strong> of the broader NYC Airbnb market. As the number of listings only contributes to a significantly small amount of the total dataset, by excluding them, we improve model stability, reduce variance, and allow clearer interpretation of pricing trends among typical listings.</p>
<p>Therefore, we revised on the plot as below:</p>
<div id="211e962a" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>sns.histplot(df[<span class="st">"price"</span>], bins<span class="op">=</span><span class="dv">50</span>, kde<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Distribution of Airbnb Prices"</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Price"</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Frequency"</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-16-output-1.png" width="825" height="523" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Insights: - The revised distribution shows a <strong>more focused and realistic range of prices</strong>, with most listings falling between $50 and $300 per night. - The <strong>modal price range</strong> (most frequent) appears to be around $100–$150. - Although still right-skewed, the distribution is much <strong>less extreme</strong> and more analytically useful for summary statistics and regression modeling. - This adjustment helps ensure that further statistical models are not dominated by rare high-end listings.</p>
</section>
<section id="distribution-of-number-of-reviews" class="level3">
<h3 class="anchored" data-anchor-id="distribution-of-number-of-reviews">Distribution of Number of Reviews</h3>
<p>To explore how frequently listings are reviewed on Airbnb, we examined the distribution of the <code>number_of_reviews</code> variable:</p>
<div id="365bd091" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Summary statistics for 'number_of_reviews':"</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">"number_of_reviews"</span>].describe())</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>sns.histplot(df[<span class="st">"number_of_reviews"</span>], bins<span class="op">=</span><span class="dv">50</span>, kde<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Distribution of Number of Reviews"</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Number of Reviews"</span>)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Frequency"</span>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Summary statistics for 'number_of_reviews':
count    40447.000000
mean        15.940119
std         29.282452
min          0.000000
25%          1.000000
50%          4.000000
75%         17.000000
max        421.000000
Name: number_of_reviews, dtype: float64</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-17-output-2.png" width="833" height="523" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Insights:</p>
<ul>
<li>The distribution is <strong>highly right-skewed</strong>, with the majority of listings having <strong>fewer than 25 reviews</strong>.</li>
<li>There are many listings with <strong>zero reviews</strong>, and only a small number exceed 100 reviews.</li>
<li>The long tail suggests that a handful of properties are booked and reviewed far more frequently than the rest — likely due to factors such as location, price, or host quality.</li>
<li>The shape of this distribution supports the use of <strong>Poisson regression</strong> for modeling count data like <code>number_of_reviews</code>, possibly with adjustments for overdispersion or zero inflation if needed.</li>
</ul>
<p>From the histogram of <code>number_of_reviews</code>, we observed that the distribution is <strong>extremely right-skewed</strong>. While most listings receive relatively few reviews, there are a small number of listings with exceptionally high review counts.</p>
<p>To quantify these potential outliers, we examined how many listings had more than 200 reviews:</p>
<div id="5d35a862" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>high_review_count <span class="op">=</span> (df[<span class="st">"number_of_reviews"</span>] <span class="op">&gt;</span> <span class="dv">100</span>).<span class="bu">sum</span>()</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Number of listings with more than 200 reviews: </span><span class="sc">{</span>high_review_count<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of listings with more than 200 reviews: 1085</code></pre>
</div>
</div>
<p>Only <strong>1,085 listings</strong> have more than 200 reviews, out of tens of thousands of entries. This confirms that <strong>a very small proportion of listings receive a disproportionately large share of reviews</strong>.</p>
<p>These outliers can heavily influence mean-based metrics and potentially distort model results.Given the extreme right skew of the <code>number_of_reviews</code> variable, we filtered the dataset to only include listings with 100 or fewer reviews — the range where most of the data lies. This allows us to better observe the underlying structure and distribution.</p>
<div id="ffdb062c" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>subset <span class="op">=</span> df[df[<span class="st">"number_of_reviews"</span>] <span class="op">&lt;=</span> <span class="dv">100</span>]</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>sns.histplot(subset[<span class="st">"number_of_reviews"</span>], bins<span class="op">=</span><span class="dv">100</span>, kde<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Distribution of Number of Reviews (0–100)"</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Number of Reviews"</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Frequency"</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-19-output-1.png" width="825" height="523" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Insights:</p>
<ul>
<li>The plot reveals a <strong>very steep drop-off</strong> in review counts: most listings have <strong>fewer than 10 reviews</strong>, with the most common value being zero.</li>
<li>There’s a <strong>long but thinner tail</strong> between 10 and 100 reviews.</li>
<li>These results reinforce that review activity is <strong>concentrated among a small number of frequently booked listings</strong>, while most receive minimal engagement.</li>
<li>This justifies modeling <code>number_of_reviews</code> as <strong>count data</strong>, likely using Poisson or negative binomial regression.</li>
</ul>
</section>
<section id="price-vs.-review-score-value" class="level3">
<h3 class="anchored" data-anchor-id="price-vs.-review-score-value">Price vs.&nbsp;Review Score (Value)</h3>
<p>To explore whether customer-perceived “value for money” correlates with listing price, we visualized the relationship between <code>price</code> and <code>review_scores_value</code> using a scatter plot:</p>
<p>We plotted each listing’s price against its corresponding <strong>value review score</strong> (1–10 scale). - <code>alpha=0.4</code> was used to reduce overplotting and make dense clusters easier to interpret. - This allows us to visually inspect whether higher prices are associated with lower perceived value, or if highly rated listings tend to be more expensive</p>
<div id="d0e95ab6" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(data<span class="op">=</span>df, x<span class="op">=</span><span class="st">"review_scores_value"</span>, y<span class="op">=</span><span class="st">"price"</span>, alpha<span class="op">=</span><span class="fl">0.4</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Price vs Review Score (Value)"</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Review Score: Value"</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Price"</span>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-20-output-1.png" width="825" height="523" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Insights:</p>
<p>The scatter plot of price against the review score for value reveals several key patterns. First, the vast majority of listings are concentrated at high review scores, particularly between 8 and 10, indicating that most guests perceive their stays as good value for money. Despite this clustering, prices vary widely within each review score category — especially at higher scores — suggesting that higher price does not necessarily equate to lower perceived value. Interestingly, some listings with very high prices (e.g., above $800) still receive value scores of 9 or 10, indicating that guests may perceive expensive listings as worthwhile if the quality or amenities justify the cost. Conversely, listings with lower value scores (below 6) are fewer in number and tend to be more scattered in price, but still include a few high-priced outliers, suggesting occasional misalignments between pricing and guest expectations. Overall, the relationship between price and value rating appears <strong>weak and non-linear</strong>.</p>
</section>
</section>
<section id="modeling-number-of-reviews-with-poisson-regression" class="level2">
<h2 class="anchored" data-anchor-id="modeling-number-of-reviews-with-poisson-regression">Modeling Number of Reviews with Poisson Regression</h2>
<p>To model the number of reviews — treated as a count variable and proxy for demand or bookings — we used a <strong>Poisson regression model</strong>, which is appropriate for count data.</p>
<section id="variables-included" class="level4">
<h4 class="anchored" data-anchor-id="variables-included">Variables Included</h4>
<p>We modeled <code>number_of_reviews</code> as a function of the following explanatory variables:</p>
<ul>
<li><code>days</code>: How long the listing has been active</li>
<li><code>bathrooms</code>, <code>bedrooms</code>: Size and features of the listing</li>
<li><code>price</code>: Cost per night</li>
<li><code>review_scores_cleanliness</code>, <code>review_scores_location</code>, <code>review_scores_value</code>: Guest satisfaction metrics</li>
<li><code>instant_bookable</code>: Binary indicator of whether the listing can be booked instantly</li>
<li><code>room_type</code>: Categorical variable (converted to dummy variables with one dropped for reference)</li>
</ul>
</section>
<section id="model-specification-and-estimation" class="level4">
<h4 class="anchored" data-anchor-id="model-specification-and-estimation">Model Specification and Estimation</h4>
<div id="1a649681" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">"number_of_reviews"</span>]</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>columns_needed_for_x <span class="op">=</span> [</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"days"</span>, <span class="st">"room_type"</span>, <span class="st">"bathrooms"</span>, <span class="st">"bedrooms"</span>, <span class="st">"price"</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"review_scores_cleanliness"</span>, <span class="st">"review_scores_location"</span>, <span class="st">"review_scores_value"</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"instant_bookable"</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df[columns_needed_for_x].copy()</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>X[<span class="st">"instant_bookable"</span>] <span class="op">=</span> X[<span class="st">"instant_bookable"</span>].<span class="bu">map</span>({<span class="st">"t"</span>: <span class="dv">1</span>, <span class="st">"f"</span>: <span class="dv">0</span>})</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> pd.get_dummies(X, columns<span class="op">=</span>[<span class="st">"room_type"</span>], drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(X)</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> X.astype(<span class="bu">float</span>)</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>poisson_model <span class="op">=</span> sm.GLM(y, X, family<span class="op">=</span>sm.families.Poisson()).fit()</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>poisson_model.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Generalized Linear Model Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>number_of_reviews</td>
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>40447</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>GLM</td>
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>40436</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Model Family:</td>
<td>Poisson</td>
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>10</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Link Function:</td>
<td>Log</td>
<td data-quarto-table-cell-role="th">Scale:</td>
<td>1.0000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>IRLS</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-6.5524e+05</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Tue, 06 May 2025</td>
<td data-quarto-table-cell-role="th">Deviance:</td>
<td>1.1868e+06</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>20:29:29</td>
<td data-quarto-table-cell-role="th">Pearson chi2:</td>
<td>1.73e+06</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. Iterations:</td>
<td>6</td>
<td data-quarto-table-cell-role="th">Pseudo R-squ. (CS):</td>
<td>0.9750</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">z</td>
<td data-quarto-table-cell-role="th">P&gt;|z|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">const</td>
<td>2.7445</td>
<td>0.018</td>
<td>149.240</td>
<td>0.000</td>
<td>2.708</td>
<td>2.781</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">days</td>
<td>0.0006</td>
<td>1.83e-06</td>
<td>346.349</td>
<td>0.000</td>
<td>0.001</td>
<td>0.001</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">bathrooms</td>
<td>-0.1045</td>
<td>0.004</td>
<td>-26.785</td>
<td>0.000</td>
<td>-0.112</td>
<td>-0.097</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">bedrooms</td>
<td>0.0875</td>
<td>0.002</td>
<td>41.740</td>
<td>0.000</td>
<td>0.083</td>
<td>0.092</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">price</td>
<td>-0.0004</td>
<td>1.57e-05</td>
<td>-27.507</td>
<td>0.000</td>
<td>-0.000</td>
<td>-0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">review_scores_cleanliness</td>
<td>0.1429</td>
<td>0.002</td>
<td>83.242</td>
<td>0.000</td>
<td>0.140</td>
<td>0.146</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">review_scores_location</td>
<td>-0.1036</td>
<td>0.002</td>
<td>-57.461</td>
<td>0.000</td>
<td>-0.107</td>
<td>-0.100</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">review_scores_value</td>
<td>-0.1146</td>
<td>0.002</td>
<td>-55.633</td>
<td>0.000</td>
<td>-0.119</td>
<td>-0.111</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">instant_bookable</td>
<td>0.5068</td>
<td>0.003</td>
<td>174.621</td>
<td>0.000</td>
<td>0.501</td>
<td>0.512</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">room_type_Private room</td>
<td>-0.0936</td>
<td>0.003</td>
<td>-31.611</td>
<td>0.000</td>
<td>-0.099</td>
<td>-0.088</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">room_type_Shared room</td>
<td>-0.2320</td>
<td>0.009</td>
<td>-26.641</td>
<td>0.000</td>
<td>-0.249</td>
<td>-0.215</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Insights:</p>
<ul>
<li><p><strong><code>days</code></strong>: Each additional day a listing has been active is associated with a small but statistically significant increase in expected reviews (( = 0.0006 )). This makes intuitive sense: the longer a listing is online, the more reviews it can accumulate.</p></li>
<li><p><strong><code>bathrooms</code></strong>: Surprisingly, listings with more bathrooms are associated with fewer reviews (beta = -0.1044). This might reflect that larger, higher-end units cater to longer stays or smaller guest segments.</p></li>
<li><p><strong><code>bedrooms</code></strong>: More bedrooms are positively associated with review count (beta = 0.0869), which aligns with the idea that larger listings can accommodate more guests and attract more traffic.</p></li>
<li><p><strong><code>price</code></strong>: The effect of price is negative but small (beta = -0.00004). Higher-priced listings receive slightly fewer reviews, all else equal, likely due to reduced accessibility or demand.</p></li>
<li><p><strong>Review scores:</strong></p>
<ul>
<li><strong><code>review_scores_cleanliness</code></strong> has a strong positive association with number of reviews (beta = 0.1425), suggesting that clean listings attract more bookings and positive feedback loops.</li>
<li><strong><code>review_scores_location</code></strong> and <strong><code>review_scores_value</code></strong> both have significant negative associations. This may reflect non-linear effects or higher expectations associated with high scores in these categories.</li>
</ul></li>
<li><p><strong><code>instant_bookable</code></strong>: One of the strongest predictors. Listings that allow instant booking receive significantly more reviews (beta = 0.5066 ), likely because they reduce friction for potential guests.</p></li>
<li><p><strong><code>room_type</code></strong>:</p>
<ul>
<li><strong>Private rooms</strong> receive fewer reviews than entire homes (beta = -0.0918 ).</li>
<li><strong>Shared rooms</strong> receive even fewer (beta = -0.2298).</li>
<li>This confirms that guests prefer private or entire accommodations — especially for longer or more frequent stays.</li>
</ul></li>
</ul>
<p>Overall, the model fits well (Pseudo R² ≈ 0.975), and the signs and magnitudes of coefficients are consistent with expectations from the Airbnb marketplace.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>